//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtOne_v1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HTONEEntities : DbContext
    {
        public HTONEEntities()
            : base("name=HTONEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SEQUENCE_TBL> SEQUENCE_TBL { get; set; }
        public DbSet<TICKER_MESSAGE_STATUS> TICKER_MESSAGE_STATUS { get; set; }
        public DbSet<TICKER_MESSAGE_TBL> TICKER_MESSAGE_TBL { get; set; }
        public DbSet<TICKER_MESSAGE_TYPE> TICKER_MESSAGE_TYPE { get; set; }
    }
}
