//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtOne_v1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEQUENCE_TBL
    {
        public string TABLE_NAME { get; set; }
        public int TABLE_NEXT_ID { get; set; }
    }
}
