//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtOne_v1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKER_MESSAGE_TBL
    {
        public int MSG_ID { get; set; }
        public string MSG_DESCR { get; set; }
        public short MSG_TYPE { get; set; }
        public short MSG_STATUS { get; set; }
        public System.DateTime ADDED_ON { get; set; }
        public string ADDED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> DELTETED_ON { get; set; }
        public string DELETED_BY { get; set; }
    }
}
