//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtOne_v1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKER_MESSAGE_STATUS
    {
        public short MSG_STATUS { get; set; }
        public string MSG_STATUS_DESCR { get; set; }
    }
}
